# action.yml
on: [push]

jobs:
  vm:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo This job does not specify a container.
          echo It runs directly on the virtual machine.
        name: Run on VM
  container:
    runs-on: ubuntu-latest
    container: node:10.16-jessie
    steps:
      - run: |
          -docker run -v /var/run/docker.sock:/var/run/docker.sock \
           -ti docker
        name: Run in container
